import type { Category, Comment, Post } from "@/types/blog";

export const categories: Category[] = [
  {
    slug: "engineering",
    name: "技术",
    description: "前端、后端、架构与工程实践的长期记录。",
    postCount: 56,
    accent: "bg-teal-50 text-teal-700",
  },
  {
    slug: "product",
    name: "产品",
    description: "产品思维、用户研究、增长实验与判断力训练。",
    postCount: 32,
    accent: "bg-blue-50 text-blue-700",
  },
  {
    slug: "design",
    name: "设计",
    description: "界面体验、设计系统、视觉秩序与协作方法。",
    postCount: 28,
    accent: "bg-violet-50 text-violet-700",
  },
  {
    slug: "life",
    name: "生活",
    description: "阅读、习惯、旅行、工具与个人节奏的观察。",
    postCount: 24,
    accent: "bg-amber-50 text-amber-700",
  },
  {
    slug: "ai",
    name: "AI",
    description: "AI 工具、工作流、应用探索与未来思考。",
    postCount: 18,
    accent: "bg-fuchsia-50 text-fuchsia-700",
  },
];

export const posts: Post[] = [
  {
    id: "post-001",
    slug: "build-a-personal-blog-system",
    title: "从 0 到 1 搭建一个个人博客系统",
    excerpt: "分享我如何从需求分析、技术选型到页面上线，独立搭建这套博客系统的全过程与踩坑经验。",
    content:
      "这篇文章记录 Maurice Notes 从想法到落地的过程：为什么需要一个独立博客、如何拆分公开站点与后台、以及怎样在早期用 mock 数据先跑通产品体验。",
    category: "技术",
    status: "published",
    author: "Maurice",
    publishedAt: "2024-05-12",
    readingTime: "8 分钟阅读",
    views: "9.1K",
    comments: 27,
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    featured: true,
  },
  {
    id: "post-002",
    slug: "product-thinking-habits",
    title: "一个产品人的 7 个习惯",
    excerpt: "从用户视角出发，整理产品设计与迭代中最重要的七个思维模型与实践方法。",
    content:
      "产品判断不是灵感闪现，而是持续观察、拆解、验证与复盘之后形成的习惯。这篇文章用几个小例子说明我如何训练这种判断力。",
    category: "产品",
    status: "published",
    author: "Maurice",
    publishedAt: "2024-05-05",
    readingTime: "6 分钟阅读",
    views: "5.6K",
    comments: 16,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
    featured: true,
  },
  {
    id: "post-003",
    slug: "visual-hierarchy-in-b2b-ui",
    title: "B 端设计中的信息层级与视觉秩序",
    excerpt: "透过实际案例，聊聊如何在复杂业务系统中建立清晰的信息层级与视觉秩序。",
    content:
      "B 端界面往往不是缺少信息，而是缺少秩序。好的层级能让用户快速定位重点，也能让复杂操作变得更可控。",
    category: "设计",
    status: "published",
    author: "Maurice",
    publishedAt: "2024-04-28",
    readingTime: "7 分钟阅读",
    views: "8.7K",
    comments: 18,
    image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=80",
    featured: true,
  },
  {
    id: "post-004",
    slug: "frontend-performance-checklist",
    title: "2024 前端性能优化清单（实战版）",
    excerpt: "系统梳理前端性能优化的关键点与实战方法，涵盖加载、渲染、网络、资源等多个维度。",
    content:
      "性能优化需要先测量，再定位瓶颈，最后选择合适的策略。这份清单覆盖我在真实项目上线前会检查的关键环节。",
    category: "技术",
    status: "published",
    author: "Maurice",
    publishedAt: "2024-05-15",
    readingTime: "9 分钟阅读",
    views: "12.4K",
    comments: 32,
    image: "https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "post-005",
    slug: "digital-garden-tools",
    title: "数字游民的效率工具箱（我的 12 个推荐）",
    excerpt: "作为一名数字游民，这些工具陪伴我完成了异时区协作、内容创作与生活管理。",
    content:
      "工具本身不是答案，但合适的工具能降低启动成本。这篇文章整理了我长期使用并保留下来的效率工具。",
    category: "生活",
    status: "draft",
    author: "Maurice",
    publishedAt: "2024-05-04",
    readingTime: "5 分钟阅读",
    views: "-",
    comments: 0,
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "post-006",
    slug: "ai-workflow-review",
    title: "我如何审查 AI 辅助完成的工作",
    excerpt: "关于在 AI 工作流中同时保留速度、判断力与验证意识的一些实践笔记。",
    content:
      "AI 可以提高速度，但不能替代判断。这篇文章记录我在写作、代码与产品工作中审查 AI 输出的几个固定步骤。",
    category: "AI",
    status: "review",
    author: "Maurice",
    publishedAt: "2024-04-25",
    readingTime: "10 分钟阅读",
    views: "-",
    comments: 4,
    image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
  },
];

export const comments: Comment[] = [
  {
    id: "comment-001",
    author: "张小明",
    postTitle: "2024 前端性能优化清单（实战版）",
    body: "资源加载那一段非常实用，已经加入我们团队的上线检查清单。",
    status: "pending",
    createdAt: "2 小时前",
  },
  {
    id: "comment-002",
    author: "Lily",
    postTitle: "B 端设计中的信息层级与视觉秩序",
    body: "关于表格密度和视觉层级的例子很具体，帮我理清了后台页面的改版方向。",
    status: "approved",
    createdAt: "昨天 22:18",
  },
  {
    id: "comment-003",
    author: "Moon",
    postTitle: "从 0 到 1 搭建一个个人博客系统",
    body: "期待后续分享编辑器、标签和订阅功能的实现过程。",
    status: "pending",
    createdAt: "2024-04-20",
  },
];
